---
# tasks file for roles/ccze

- include: centos7.yml
  when:
   - ansible_distribution == "CentOS"
   - ansible_distribution_major_version == "7"

- include: ubuntu18.yml
  when:
   - ansible_distribution == "Ubuntu"
   - ansible_distribution_major_version == "18"

- include: ubuntu20.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "20"
