---
# tasks file for vim8
# For Ubuntu18
- name: Get hostname
  command: bash -lc "hostname"
  register: hostname
  changed_when: False
  ignore_errors: yes

- name: Get Compiled
  shell: "vim --version | grep 'Compiled by'"
  register: compiled_by
  changed_when: False
  ignore_errors: yes

- name: Display compiled
  debug:
    msg: "{{ compiled_by.stdout }}"


- name: Display target compiled
  debug:
    msg: "Compiled by {{ ansible_env.LOGNAME }}@{{ hostname.stdout }}"

- name: check installed vim8
  #shell: bash -lc "vim --version"
  shell: "vim --version | grep {{ ansible_env.LOGNAME }}@{{ hostname.stdout }}"
  register: vim8_exists
  changed_when: False
  ignore_errors: yes

- name: debug Compiled by
  debug:
    msg: "{{ compiled_by.stdout }}"

- name: Install dependencies for vim8
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ vim8_dependencies }}"
  when:
   - vim8_exists is failed
