---
# tasks file for tmuxinator
# For ubuntu18
# tasks file for bundle
- name: Check gems installed
  shell: >-
    bash -lc "{{ rbenv_path }}/shims/gem list | grep {{ item.name }}
    {% if item.version is defined %}
     | grep '({{ item.version }}[).]'
    {%- endif -%}
     | wc -l"
  register: check_gem_install
  changed_when: False
  ignore_errors: yes
  check_mode: no
  with_items: "{{ gems | default([]) }}"

- name: Save Checking gems results
  set_fact:
    gem_chk: >-
      {%- set cnt = [] -%}
      {%- for i in check_gem_install.results -%}
      {%-   if i.stdout == "0" -%}
      {%-     set _ = cnt.append(i.stdout) -%}
      {%-   endif -%}
      {%- endfor -%}
      {{ cnt | length }}
  changed_when: False

- name: install gems
  shell: >-
    bash -lc "{{ rbenv_path }}/shims/gem install {{ item.name }}
    {% if item.version is defined %}
     -v {{ item.version }}
    {%- endif %}"
  register: result
  until: result.rc == 0
  retries: 5
  delay: 10
  with_items: "{{ gems | default([]) }}"
  when: not ansible_check_mode and gem_chk != "0"
