---
# tasks file for roles/pwgen
# For Ubuntu18
- name: check installed pwgen
  command: bash -lc "pwgen"
  register: pwgen_exists
  changed_when: False
  ignore_errors: yes


- name: Install pwgen
  become: yes
  apt:
    name: "pwgen"
    state: present
  when: pwgen_exists is failed

