---
# tasks file for roles/hostname
- name: Check hostname
  become: true
  command: bash -lc "hostname"
  register: check_hostname
  changed_when: False

- name: Set hostname
  become: true
  command: bash -lc "hostnamectl set-hostname {{ hostname }}"
  when: check_hostname.stdout != hostname

