---
# defaults file for Group develop
# common
hostname: 'develop.local'
home_path: "{{ ansible_env.HOME }}"
deploy_path: "{{ home_path }}/ansible"
login_shell: 'zsh'
#ansible
ansible_state: "present"
#ansible_state: "absent"

# golang
golang_version: 1.13.4
goenv_state: "present"

#python
pyenv_state: "present"
#pyenv_state: "absent"
pyenv_path: "{{ home_path }}/.pyenv"
python_version: 3.7.6

#ruby
rbenv_path: "{{ home_path }}/.rbenv"
ruby_version: 2.6.3
gems:
  - name: bundler
  - name: serverspec
  - name: ansible_spec

#php
phpenv_path: "{{ home_path }}/.phpenv"
php_version: 7.3.15
install_php: false

#lua
luaenv_path: "{{ home_path }}/.luaenv"
lua_version: 5.3.5

#node
nodenv_path: "{{ home_path }}/.nodenv"
node_version: 12.16.1


#docker-compose
docker_compose_version: 1.25.5

#bash_it theme
bash_it_theme: bobby

#oh-my-zsh theme
oh_my_zsh_theme: 'suvash'

#global
global_state: "present"
global_version: '6.6.3'
