---
# tasks file for rbenv
# For Ubuntu18
- name: Install dependencies for ruby-build (see. https://github.com/sstephenson/ruby-build/wiki)
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ruby_dependencies }}"


