---
# tasks file for tmux
# For ubuntu18
- name: Install dependencies for tmux
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ tmux_dependencies }}"
  when: tmux_exists is failed
