---
# tasks file for roles/ctags
- name: check installed ctags
  command: bash -lc "ctags --version"
  register: ctags_exists
  changed_when: False
  ignore_errors: yes

- include: centos7.yml
  when:
   - ansible_distribution == "CentOS"
   - ansible_distribution_major_version == "7"
   - ctags_exists is failed

- include: ubuntu18.yml
  when:
   - ansible_distribution == "Ubuntu"
   - ansible_distribution_major_version == "18"
   - ctags_exists is failed

- include: ubuntu20.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "20"
    - ctags_exists is failed
